name: Build and deploy prenoms API

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug 1
        run: ls -l

      - uses: actions/checkout@v3

      - name: Debug 2
        run: ls -l