name: deploy to Composer

on: []

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Auth GCP gcloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Upload schema folder
      run: gcloud composer environments --project ensai-2024 storage dags import --location europe-west1 --environment prod --source energy/dags/schema/

    - name: Upload sql folder
      run: gcloud composer environments --project ensai-2024 storage dags import --location europe-west1 --environment prod --source energy/dags/sql/

    - name: Upload extract DAG
      run: gcloud composer environments --project ensai-2024 storage dags import --location europe-west1 --environment prod --source energy/dags/extract_and_load_energy_data.py